# Generated by Django 4.0.3 on 2022-04-24 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import zero_note.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('users', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Food', 'Food'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Healthcare', 'Healthcare'), ('Debt', 'Debt'), ('Personal', 'Personal'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='title',
        ),
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Food', 'Food'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Healthcare', 'Healthcare'), ('Debt', 'Debt'), ('Personal', 'Personal'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='budget',
            name='sheet',
            field=models.ForeignKey(default=zero_note.core.models.BudgetSheet.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='core.budgetsheet'),
        ),
    ]
